# ده اللي هيكون في Git
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "{cipher}a636753d35283c7d593e06a749088a150a7212d25f41d0e4784050e09a6770b7"
    password: "{cipher}a636753d35283c7d593e06a749088a150a7212d25f41d0e4784050e09a6770b7"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
