# ده اللي هيكون في Git
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "{cipher}502e9645e859002d6e508b321c502382ea40afe0b8c57a1757e3a35c5c07d704"
    password: "{cipher}502e9645e859002d6e508b321c502382ea40afe0b8c57a1757e3a35c5c07d704"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
