server:
  port: 8070   # 👈 Eureka هيشتغل على 8070 جوا الكونتينر

spring:
  application:
    name: eureka-service   # اسم الخدمة في Spring Cloud

eureka:
  instance:
    hostname: eureka-service   # 👈 مهم: ده اسم الخدمة في docker-compose مش localhost
  client:
    register-with-eureka: false   # السيرفر مايسجلش نفسه
    fetch-registry: false         # السيرفر مايحاولش يجيب registry من نفسه
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
